import argparse
import pathlib
from typing import Dict, List

from validate_contracts import extract_policy_data, validate_contract


def _escape_cpp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _cpp_string_list(values: List[str]) -> str:
    if not values:
        return ""
    return ",\n    ".join(f'\"{_escape_cpp_string(v)}\"' for v in values)


def _cpp_bool(value: bool) -> str:
    return "true" if value else "false"


def _build_header(soul: Dict, agents: Dict) -> str:
    stt_order = soul["stt"]["evaluation_order"]
    empty_input_decision = soul["stt"]["rules"]["empty_input"]["decision"]

    timeout = soul["session"]["listening_timeout"]
    timeout_decision = soul["session"]["timeout_decision"]

    intent = agents["intent"]
    precedence = intent["precedence"]

    keyword_csv: List[str] = []
    for intent_name in precedence:
        words = intent["keyword_sets"].get(intent_name, [])
        keyword_csv.append(",".join(words))

    return f"""// This file is generated by tools/contracts/compile_contracts.py.
// Do not edit manually.
#ifndef POLICY_BUNDLE_V1_H_
#define POLICY_BUNDLE_V1_H_

#include <cstddef>

namespace policy {{
namespace generated {{

inline constexpr const char* kSttEvaluationOrder[] = {{
    {_cpp_string_list(stt_order)}
}};
inline constexpr std::size_t kSttEvaluationOrderCount = {len(stt_order)};

inline constexpr const char* kEmptyInputDecisionAction = \"{_escape_cpp_string(empty_input_decision['action'])}\";
inline constexpr const char* kEmptyInputDecisionReason = \"{_escape_cpp_string(empty_input_decision['reason'])}\";
inline constexpr const char* kEmptyInputRepromptKey = \"{_escape_cpp_string(empty_input_decision['reprompt_key'])}\";

inline constexpr const char* kListeningTimeoutSource = \"{_escape_cpp_string(timeout['source'])}\";
inline constexpr const char* kListeningTimeoutConfigKey = \"{_escape_cpp_string(timeout['config_key'])}\";

inline constexpr const char* kTimeoutDecisionAction = \"{_escape_cpp_string(timeout_decision['action'])}\";
inline constexpr const char* kTimeoutDecisionReason = \"{_escape_cpp_string(timeout_decision['reason'])}\";
inline constexpr const char* kTimeoutRepromptKey = \"{_escape_cpp_string(timeout_decision['reprompt_key'])}\";
inline constexpr bool kTimeoutResetClock = {_cpp_bool(bool(timeout_decision['reset_clock']))};

inline constexpr const char* kIntentNames[] = {{
    {_cpp_string_list(precedence)}
}};
inline constexpr const char* kIntentKeywordCsv[] = {{
    {_cpp_string_list(keyword_csv)}
}};
inline constexpr std::size_t kIntentCount = {len(precedence)};

}}  // namespace generated
}}  // namespace policy

#endif  // POLICY_BUNDLE_V1_H_
"""


def compile_contracts(
    soul_path: pathlib.Path,
    agents_path: pathlib.Path,
    schema_path: pathlib.Path,
    out_path: pathlib.Path,
) -> None:
    validate_contract(soul_path, schema_path)
    validate_contract(agents_path, schema_path)

    soul_policy = extract_policy_data(soul_path.read_text(encoding="utf-8"))
    agents_policy = extract_policy_data(agents_path.read_text(encoding="utf-8"))

    header = _build_header(soul_policy, agents_policy)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(header, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--soul", required=True)
    parser.add_argument("--agents", required=True)
    parser.add_argument("--schema", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    compile_contracts(
        pathlib.Path(args.soul),
        pathlib.Path(args.agents),
        pathlib.Path(args.schema),
        pathlib.Path(args.out),
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
